server:
  port: ${PORT:8762}

spring:
  application:
    name: containerized-gateway

  cloud:
    gateway:
      routes:
        - id: CONTAINERIZED-users
          uri: lb://CONTAINERIZED-USERS
          predicates:
            - Path=/user/**

management:
  endpoints:
    web:
      exposure:
        include: "*"

  metrics:
    distribution:
      percentiles-histogram.http.server.requests: false
      percentiles.http.server.requests: 0.5, 0.9, 0.95, 0.99, 0.999
      sla.http.server.requests: 500ms, 2000ms

eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: false
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://discovery:8761}/eureka

# Increase the Hystrix timeout to 60s (globally)
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
